### ISSUE TITLE
Fastest NTT

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/twenty-first#1]
This paper from Microsoft Research seems to contain a pseudo-algorithm for what is probably the optimal NTT implementation.

https://eprint.iacr.org/2016/504.pdf

Another article about a fast NTT:
https://crypto.ethz.ch/publications/files/Seiler18.pdf

**Comment by Sword-Smith** [comment]
With @Munksgaard's help and by using `--release` the runtime over the field with prime `p=167772161`, the runtime has been brought down from 17 seconds on my Dell XPS to 2 seconds on a data set with `2^20` `i64` entries.

I have not yet managed to implement the algorithm from Microsoft Research linked above though.

**Comment by Sword-Smith** [comment]
There is something called "bit-reversal" ordering in the Microsoft Research article that I don't know what means.

**Comment by Munksgaard** [comment]
Perhaps this is what they mean? https://en.wikipedia.org/wiki/Bit-reversal_permutation

**Comment by Sword-Smith** [comment]
> Perhaps this is what they mean? https://en.wikipedia.org/wiki/Bit-reversal_permutation

That makes sense as the input always has length 2^n so such a permutation should be possible. So we need to map the value a index `000->000` and `011->110`?

**Comment by Sword-Smith** [comment]
Might be what is implemented here: https://github.com/dusk-network/plonk/blob/d3412cec5fa5c2e720f848a6fd8db96d663e92a9/src/fft/domain.rs#L310
