### ISSUE TITLE
Don't be multi-crate

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/twenty-first#117]
After deleting the deprecated Rescue Prime and Brainfuck STARKs in 765973835e09452a515b2ba72869b4b7ba16c678, this repo no longer needs to be a multi-crate repository.

**Comment by sshine** [comment]
The benefit of being a multi-crate repository is that you can merge it into any other multi-crate repository.

Having non-overlapping sub-directories makes the crate easier to move around.

By merging the singleton crate with the triton-vm repo, you could argue that this repo no longer needs to be a repo.

**Comment by Sword-Smith** [comment]
> The benefit of being a multi-crate repository is that you can merge it into any other multi-crate repository.
> 
> Having non-overlapping sub-directories makes the crate easier to move around.
> 
> By merging the singleton crate with the triton-vm repo, you could argue that this repo no longer needs to be a repo.

I see. We can stay multi-crate then, I guess. Not sure I would want to merge this into Triton VM, as it contains a lot of cryptography that has a value on its own.

**Comment by sshine** [comment]
> Not sure I would want to merge this into Triton VM, as it contains a lot of cryptography that has a value on its own.

Is twenty-first being used in a project that doesn't also depend on triton-vm?

What is the compelling argument to use twenty-first over, say, [arkworks-rs/algebra](https://github.com/arkworks-rs/algebra/)?

If twenty-first lived in the triton-vm repository, it would still be a stand-alone crate available on crates.io.

But it might get less publicity. So perhaps that is the best reason to let it stay in its own repository.

**Comment by Sword-Smith** [comment]
> > Not sure I would want to merge this into Triton VM, as it contains a lot of cryptography that has a value on its own.
> 
> Is twenty-first being used in a project that doesn't also depend on triton-vm?
> 
> What is the compelling argument to use twenty-first over, say, [arkworks-rs/algebra](https://github.com/arkworks-rs/algebra/)?
> 
> If twenty-first lived in the triton-vm repository, it would still be a stand-alone crate available on crates.io.
> 
> But it might get less publicity. So perhaps that is the best reason to let it stay in its own repository.

This might happen in the future. Last time I checked though, two years ago, there was e.g. no good Rust crate implementing Merkle trees, and none implementing Merkle Moutain Ranges. If those things were to be used, twenty-first could stay independent.

Either way I like to make these changes only after I've been convinced of them for some time which is why the Rescue Prime and Brainfuck STARKs were removed only just yesterday and not months ago.
