### ISSUE TITLE
support tuple fields in derive macro `BFieldCodec`

### ISSUE THREAD

**Issue by jan-ferdinand** [Neptune-Crypto/twenty-first#121]
Structs with tuples as fields are not supported by the current derive macro `BFieldCodec`. More specifically, deriving the trait will succeed, and the resulting implementations of `encode` and `decode` will compile. However, the derived methods `encode` and `decode` won't be each others duals. For example, the following code will panic.

```rust
#[derive(BFieldCodec)]
struct Foo((u8, u8));
let encoded = Foo((1, 2)).encode();
let decoded = Foo::decode(&encoded).unwrap();
```

This is possibly caused by missing or incomplete implementations of `GetSize` for tuples. Deriving their size using macros like [`get_size_derive`](https://docs.rs/get-size-derive/0.1.2/get_size_derive/) is not possible with their current version v0.1.2.

Figure out a way to support tuple fields for derive macro `BFieldCodec`.

**Comment by Sword-Smith** [comment]
This is now supported, as evidenced by this test (not committed, as similar stuff is already covered) passing:

```rust
        #[test]
        fn testtesttest() {
            #[derive(BFieldCodec, PartialEq, Eq, Debug)]
            struct Foo((u32, u32));
            let orig = Foo((1, 2));
            let encoded = orig.encode();
            let decoded = *Foo::decode(&encoded).unwrap();
            assert_eq!(orig, decoded);
        }
```
