### ISSUE TITLE
BFieldCodec encoding must be unique

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/twenty-first#126]
10a2f149894cf2fe9e4a08179be4d9b0ced65024 changes a behavior of `BFieldCodec::decode` for `Option<T>` to only accept `0` or `1` as enum indicators representing `None` and `Some`, respectively. Prior to that commit any non-zero value would indicate the `Some` variant. 

Since we are hashing these encodings and using them in a cryptographic context, it seems to me that we need to ensure uniqueness in the allowed encoding of all data structures.

- [ ] Add to the `prop` test helper function in `src/shared_math/bfield_codec.rs` some bit flipping of the encoded data structure and ensure that their decoding either fails or returns a different value.
- [ ] Manually inspect `encode` and `decode` implementations to ensure encoding-uniqueness.

**Comment by jan-ferdinand** [comment]
I do not believe that uniqueness can be achieved unless we limit what can be encoded. For example, as long as I'm free to do

```rust
#[derive(Debug, Clone, PartialEq, Eq, BFieldCodec)]
struct A {
    a: BFieldElement,
}

#[derive(Debug, Clone, PartialEq, Eq, BFieldCodec)]
struct B {
    b: u32,
}

let some_u32: u32 = random();
let bfe = BFieldElement::from(some_u32);
let my_a = A { a: bfe };
let encoding = my_a.encode();
let my_b = B::decode(&encoding).unwrap();

assert_eq!(my_a.a.value(), my_b.b as u64);
```

I don't see how uniqueness of the encoding can be achieved.

**Comment by jan-ferdinand** [comment]
Perhaps more importantly, being able to define _how_ the encoding works kills uniqueness. A counterargument to above example is to include the unique name of the struct in the encoding, and yes, that thwarts my counterexample above. But only if this is enforced for everything that can be encoded.

**Comment by Sword-Smith** [comment]
I only mean uniqueness under the assumption that the type is known.

**Comment by aszepieniec** [comment]
> I only mean uniqueness under the assumption that the type is known.

This is a useful restriction but I still find it unsettling that objects of different types can have the same hash.

**Comment by jan-ferdinand** [comment]
Please re-open if you think this is still an issue.
