### ISSUE TITLE
Add Key Prefix to DbtSingleton to avoid collisions.

### ISSUE THREAD

**Issue by dan-da** [Neptune-Crypto/twenty-first#177]
In issue #163, @Sword-Smith commented:

> 1. I notice that `DbtSingletonPrivate` doesn't have a `key_prefix` value like `DbtVecPrivate` has. Shouldn't it have that to guarantee that key-collissions cannot happen?

I'm opening this issue for discussion.

**Comment by dan-da** [comment]
Ok, after looking into this a little bit, I don't see value in modifying DbtSingleton.

In the case of DbtVec, the key-prefix is there because DbtVec will be creating many DB entries.   Eg, with prefix "apple", we will have:

```
apple: 4  (length)
apple-0: <val>
apple-1: <val>
apple-2: <val>
apple-3: <val>
```

But in the case of a Singleton, "orange", we have a field "key", and the data will look like:
```
orange: <val>
```

A singleton only ever stores a single value.   So effectively `key` in DbtSingleton and `key-prefix` in DbtVec serve the same purpose of identifying the DB key.

A kinda confusing thing is that DbtVec also includes a `name` field and DbtSingleton does not, but that is unrelated and just used for logs, etc.

-----

With regards to preventing collisions, I don't think we can really.   It is the app's responsibility to use unique identifiers.  And if an app wants to namespace a key, it certainly can, eg: "fruit-orange", "fruit-apple", "fruit-pear", etc.

----

So I recommend closing this issue, but will leave it open for comment.  I may be missing something.

**Comment by Sword-Smith** [comment]
> In the case of DbtVec, the key-prefix is there because DbtVec will be creating many DB entries. Eg, with prefix "apple", we will have: ...
From what I can see in `new_vec` in `storage_schema/schema.rs` the prefix is always a `u8`, and it simply counts how many vectors have already been declared for this schema. Whereas the key used in `dbtsingleton.rs` can be anything. So if I picked `(0u8, 0u8)` as key for the singleton, the singleton would collide with the length of the `DbtVec`, I believe.

**Comment by Sword-Smith** [comment]
Here's a test that illustrates the problem. Adding a prefix to singleton solves the problem

```rust
    #[test]
    fn singleton_vector_key_collission() {
        let db = DB::open_new_test_database(false, None, None, None).unwrap();
        let db_path = db.path().clone();
        let mut rusty_storage = SimpleRustyStorage::new(db);
        let vector1 = rusty_storage.schema.new_vec::<u64>("test-vector1");
        let singleton = rusty_storage
            .schema
            .new_singleton::<u64>(RustyKey([0u8; 2].to_vec()));

        // initialize
        rusty_storage.restore_or_new();
        assert!(vector1.is_empty());
        // vector1.push(101u64);
        singleton.set(1776u64);
        assert!(vector1.is_empty());
        rusty_storage.persist();
        assert!(vector1.is_empty());

        drop(rusty_storage); // <-- DB ref dropped
        drop(vector1); //       <-- DB ref dropped
        drop(singleton); //     <-- final DB ref dropped (DB closes)

        // re-open DB / restore from disk
        let new_db = DB::open_test_database(&db_path, true, None, None, None).unwrap();
        let mut new_rusty_storage = SimpleRustyStorage::new(new_db);
        let new_vector1 = new_rusty_storage.schema.new_vec::<S>("test-vector1");
        new_rusty_storage.restore_or_new();
        assert!(new_vector1.is_empty());
    }

```
