### ISSUE TITLE
Implement `Display` for amount types.

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/twenty-first#26]
Both `DyadicRationals` and `U32s` should implement `Display`.

- [x] `impl Display for U32s<N>`
- [ ] `impl Display for DyadicRationals`

**Comment by einar-triton** [comment]
`impl Display for U32s<N>` incl. `Amount` has been merged in #29.

**Comment by Sword-Smith** [comment]
`DyadicRationals` was removed in c358415301267982e490637ef0467e7a318e9452.
