### ISSUE TITLE
Version 0.1.4 includes breaking changes

### ISSUE THREAD

**Issue by nox** [Neptune-Crypto/twenty-first#28]
The crate ecosystem follows semver with a twist: for versions 0.y.z, y is considered to be the major version and 0.y.z+1 should be compatible with 0.y.z. Unfortunately, 0.1.4 has a lot of breaking changes compared to 0.1.3.

https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility

Could you consider yanking 0.1.4, releasing 0.1.3 again as 0.1.5, and releasing 0.1.4 as 0.2.0? This should fix any compat issues downstream.

Regards.

**Comment by sshine** [comment]
> Could you consider yanking 0.1.4, releasing 0.1.3 again as 0.1.5, and releasing 0.1.4 as 0.2.0?

That sounds like the right way forward, thank you.
