### ISSUE TITLE
impl From<i32> for BFieldElement

### ISSUE THREAD

**Issue by jan-ferdinand** [Neptune-Crypto/twenty-first#32]
It can be very convenient to execute `2.into()` and get a BFieldElement. Rust seems to default to i32's often. Thus, a conversion from i32 to BFieldElement might be handy. From a previous conversation [here](https://github.com/TritonVM/triton-vm/pull/59/):

@sshine wrote:
> I'm uncertain about that. `From<i32> for BFieldElement` seems bad.
>
> It makes sense if you think of the `i32` as a field element that wasn't cast yet.
>
> As with `From<u64> for BFieldElement`, these instances break certain expectations about arithmetic where you kind of have to accept that `i32`s and `u64`s sometimes have modular arithmetic properties with some implicit modulo, if they happen to live near `BFieldElement`s.
>
> I'd expect $\forall x:$`BFieldElement::from(x).value() == u64::from(x)`.
>
> The only perfect conversion that we have great use of is `From<u32> for BFieldElement`.
>
> If we're looking for syntactic convenience, we could consider a macro.
>
> @jan-ferdinand:
> A macro does actually sound like it could make sense.

**Comment by aszepieniec** [comment]
What behavior would you expect for negative integers?

**Comment by jan-ferdinand** [comment]
Very “big” B-Field elements.

**Comment by aszepieniec** [comment]
That choice would imply
```
BFieldElement::from<i32>(i32::max) + BFieldElement::from<i32>(1) == BFieldElement::from<i32>(i32::min)
```
which is controversial and counter-intuitive. And I would argue, also prone to error.

**Comment by aszepieniec** [comment]
> That choice would imply [...]

Actually, this line of code seems to be wrong. But there's an intuition here that still makes the point.

**Comment by aszepieniec** [comment]
Actually, I can't find examples that violate intuition and that do not involve multiplication or back-conversions. As the space of formulas that violate intuition is constrained to convoluted formulas, I concede that this choice is intuitively correct.

**Comment by aszepieniec** [comment]
> I'd expect $\forall$ `x` : `BFieldElement::from(x).value() == u64::from(x)`.

I don't see why this proposition is intuitively correct.

Furthermore, if we define `BFieldElement::from<i32>` then there are `x`s for which the left hand side succeeds and the right hand side fails.

**Comment by aszepieniec** [comment]
> If we're looking for syntactic convenience, we could consider a macro.

Syntactic convenience is one thing, but we also need instant conversions. These occur when defining round constants or matrix coefficients as `const u64`s, even though you know that the values correspond to valid BFieldElements. I considered defining the const variables as BFieldElements directly but this workflow is less conducive to copying the constants and coefficients to somewhere else or from the Sage script that generated them.

**Comment by sshine** [comment]
From [the trait's docs](https://doc.rust-lang.org/std/convert/trait.From.html):

> **Note: This trait must not fail.** The From trait is intended for perfect conversions. If the conversion can fail or is not perfect, use [TryFrom](https://doc.rust-lang.org/std/convert/trait.TryFrom.html).

You could argue that `From<i32> for BFieldElement` does not cause loss of information.

You could not argue that `From<u64> for BFieldElement` doesn't.

Of the number type conversions we apply, only `From<u32> for BFieldElement` maps every `u32` to an unsurprising `BFieldElement`.

Nothing prevents us from having a function that accepts the constants; this is currently called `BFieldElement::new(value: u64)`.

Embedding a group-theoretic conversion in a `From` is not what you'd expect.

**Comment by aszepieniec** [comment]
If I understand correctly, you are classifying potential loss of information as failure or imperfect conversion. I'm not sure this classification is incorrect. The map from the integers to the field is well defined for all integers, and it does not fail or exhibit imperfections in any mathematical sense when modular reduction occurs. I would expect failure to describe situations where the given input cannot be mapped into the target type, like for instance `EvenNumber::from(3)`.

> Nothing prevents us from having a function that accepts the constants; this is currently called `BFieldElement::new(value: u64)`.

The relevant difference (currently) between `from` and `new` is that `new` checks the argument's size and performs modular reduction if necessary; whereas `from` assumes the argument is already between 0 and p-1.

**Comment by sshine** [comment]
Yes, when the domain is larger than the range, I would not call that a perfect conversion.

If the purpose of `u64` were to contain non-normalised field elements, and isn't just incidentally used for it, the conversion would make sense.

If `impl From<u64> for BFieldElement` is perfect, are `impl From<i32> for u32` and `impl From<u64> for i64` also?

**Comment by aszepieniec** [comment]
> If the purpose of u64 were to contain non-normalised field elements, and isn't just incidentally used for it, the conversion would make sense.

My understanding is that this is exactly what happens under the hood. And that's also the reason why you need to call `.value()` to make sure the value you get is less than $p$.

**Comment by aszepieniec** [comment]
> If `impl From<u64> for BFieldElement` is perfect, are `impl From<i32> for u32` and `impl From<u64> for i64` also?

I would say no, and the reason is that `u32::from(-1i32)` should fail. The same for `impl From<u64> for i64`. While there are maps from domain to range, all of them break arithmetic. That is to say, there isn't one map that's obviously correct because it is preserves arithmetic properties.

**Comment by sshine** [comment]
The scenario I'm trying to avoid is taking some `u64` value that represents something that isn't a non-normalised field element (e.g. a size or quantity of something) and by `.into()`'ing / `BFieldElement::from`'ing it, we suddenly have a much smaller number, because those are really different representations of the same number in the field. We can't say that this conversion is meaningful for all uses we have of `u64`s, so the instance becomes dangerous.

**Comment by aszepieniec** [comment]
There are `x : u64` such that `BFieldElement::from(x).value() != x`. There are no `x : u64` such that `BFieldElement::from(x).value()` is ambiguous or ill-defined.

> We can't say that this conversion is meaningful for all uses we have of `u64`s, so the instance becomes dangerous.

The context here is a value `x` that should be a BFieldElement. With that context, we should only care about arithmetic and operations that make sense for BFieldElements. Any discrepancies arise from trying to lift the BFieldElement to a different type and use the operations defined there.

**Comment by Sword-Smith** [comment]
Is this still relevant? I think `triton-vm` has its own solution for this such that it's not needed for `twenty-first`.

**Comment by jan-ferdinand** [comment]
I think it is not relevant anymore.
