### ISSUE TITLE
Add `inverse_or_zero()` to {B, X}FieldElement

### ISSUE THREAD

**Issue by jan-ferdinand** [Neptune-Crypto/twenty-first#33]
In Triton VM, it is a common pattern to invert a field element if it the element is non-zero. Instead of writing the same code all the time, supply method `mul_inverse_or_zero()`.

**Comment by aszepieniec** [comment]
I think the prefix `mul_` is rather superfluous. Yes, technically speaking there is also such a thing as additive inverse. But without disambiguation, "inverse" always denotes _multiplicative_ inverse.
