### ISSUE TITLE
Is it a problem that this implementation generates the same BFieldElement for two different `usize` values? 

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/twenty-first#37]
This seems to have been a part of the upgrade to 0.2.0 which included a rewrite of the `Hasher` trait.

**Comment by aszepieniec** [comment]
I assume this comment refers to this code snippet, from `simple_hasher.rs` lines 190-194:
```
impl Hashable<BFieldElement> for usize {
    fn to_sequence(&self) -> Vec<BFieldElement> {
        vec![BFieldElement::new(*self as u64)]
    }
}
```

I don't think this type conversion is currently used in a way that causes problems but it might be cause problems in the future. I think the more robust solution is to drop it (and disallow the conversion from `usize` to `Vec<BFieldElement>`). If we want to cast from integers to `Vec<BFieldElement>` we should know the max size of that integer and guarantee that it behaves the same on all platforms.

**Comment by Sword-Smith** [comment]
`Hashable` has been replaced by `BFieldCodec`, and `BFieldCodec` is not implemented for `usize`, not should it be.
