### ISSUE TITLE
Unused functions in `shared_math/other.rs`

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/twenty-first#53]
E.g. `mod_pow_raw` is unused in `shared_math/other.rs`. It's implemented with the `%` operator which is **much** slower than the B-field specialized operations we have for `BFieldElement` and for `XFieldElement`. It should be removed, so no one uses it accidently.

Doing this, one should also `grep` after all other functions in `other.rs` and remove those that are unused. If a function is only called by a test, it should also be removed.

**Comment by Sword-Smith** [comment]
Notice that solving this issue will bump the version to next major version (currently that would be 0.4.0) as this is a public function and this change is thus a breaking change.

**Comment by sshine** [comment]
Removed all unused functions in this file in #55.
